language: node_js
node_js:
  - "stable"
cache:
  directories: -node_modules

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleaning: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
