version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  backend:
    container_name: docker-mytinerary-backend
    restart: always
    build: .
    image: docker/backend
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
  frontend:
    container_name: docker-mytinerary-frontend
    build: ./client
    image: docker/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
